# Generated by Django 2.0.5 on 2018-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180517_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('TASK', 'Task'), ('CREDIT_REQUEST', 'Credit Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('CASE', 'Case'), ('TASK', 'Task')], max_length=20),
        ),
    ]
